[plate]
servo_x_pin = 0
servo_y_pin = 0

[detector]
# ball detector's color detection range
lower = [90, 20, 20]
upper = [200, 50, 50]
part_search_size = [700, 700]

[mode]
button_pin = 0

[client]
url = ""
